apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: najemniski-sos
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: najemniski-sos
    newName: rg.fr-par.scw.cloud/djnd/najemniski-sos
    newTag: 'a5c6d1d41740f593cd1a253d47ed67de4a0eb2c4'
