apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: najemniski-sos
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: najemniski-sos
    newName: rg.fr-par.scw.cloud/djnd/najemniski-sos
    newTag: 'b1746562d633f5e77ab7eef9f399929fcde55ec0'
