# Generated by Django 3.2.6 on 2021-08-03 13:56

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("home", "0003_auto_20210803_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "color_section",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("white", "Bela"),
                                                        ("yellow", "Rumena"),
                                                        ("purple", "Vijolična"),
                                                        (
                                                            "gradient_green_yellow",
                                                            "Zeleno-rumena",
                                                        ),
                                                        (
                                                            "gradient_purple_green",
                                                            "Vijolično-zelena",
                                                        ),
                                                    ],
                                                    label="Barva",
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.core.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "headline",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_left",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na levi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Naslov",
                                                                template="home/blocks/headline.html",
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                default="",
                verbose_name="Vsebina",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "color_section",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("white", "Bela"),
                                                        ("yellow", "Rumena"),
                                                        ("purple", "Vijolična"),
                                                        (
                                                            "gradient_green_yellow",
                                                            "Zeleno-rumena",
                                                        ),
                                                        (
                                                            "gradient_purple_green",
                                                            "Vijolično-zelena",
                                                        ),
                                                    ],
                                                    label="Barva",
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.core.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "headline",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_left",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na levi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Naslov",
                                                                template="home/blocks/headline.html",
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                default="",
                verbose_name="Vsebina",
            ),
        ),
        migrations.CreateModel(
            name="MetaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_links",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "page_link",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Če je prazno se uporabi naslov strani.",
                                                label="Ime",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Stran"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.core.blocks.CharBlock(label="Ime"),
                                        ),
                                        (
                                            "url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Povezava"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        verbose_name="Povezave v glavi",
                    ),
                ),
                (
                    "footer_links",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "page_link",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Če je prazno se uporabi naslov strani.",
                                                label="Ime",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Stran"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.core.blocks.CharBlock(label="Ime"),
                                        ),
                                        (
                                            "url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Povezava"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        verbose_name="Povezave v nogi",
                    ),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("share_email_text", models.TextField(blank=True, null=True)),
                ("share_twitter_text", models.TextField(blank=True, null=True)),
                (
                    "meta_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta nastavitve",
            },
        ),
    ]
