# Generated by Django 3.2.6 on 2021-08-07 14:05

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20210804_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "color_section",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("white", "Bela"),
                                                        ("yellow", "Rumena"),
                                                        ("purple", "Vijolična"),
                                                        (
                                                            "gradient_green_yellow",
                                                            "Zeleno-rumena",
                                                        ),
                                                        (
                                                            "gradient_purple_green",
                                                            "Vijolično-zelena",
                                                        ),
                                                    ],
                                                    label="Barva",
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.core.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "headline",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_left",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na levi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "buttons",
                                                                        wagtail.core.blocks.StreamBlock(
                                                                            [
                                                                                (
                                                                                    "button",
                                                                                    wagtail.core.blocks.StructBlock(
                                                                                        [
                                                                                            (
                                                                                                "style",
                                                                                                wagtail.core.blocks.ChoiceBlock(
                                                                                                    choices=[
                                                                                                        (
                                                                                                            "underlined",
                                                                                                            "Samo podčrtan",
                                                                                                        ),
                                                                                                        (
                                                                                                            "normal",
                                                                                                            "Z obrobo",
                                                                                                        ),
                                                                                                        (
                                                                                                            "background",
                                                                                                            "Z obrobo in ozadjem",
                                                                                                        ),
                                                                                                    ],
                                                                                                    label="Stil gumba",
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "text",
                                                                                                wagtail.core.blocks.CharBlock(
                                                                                                    label="Besedilo na gumbu"
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "page",
                                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                                    label="Stran"
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        label="Gumb",
                                                                                    ),
                                                                                )
                                                                            ],
                                                                            label="Gumbi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Naslov",
                                                                template="home/blocks/headline.html",
                                                            ),
                                                        ),
                                                        (
                                                            "newsletter",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "submit_button",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Besedilo na gumbu"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "checkbox_text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Pogoji"
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Obvestilnik",
                                                                template="home/blocks/newsletter.html",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                default="",
                verbose_name="Vsebina",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "color_section",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("white", "Bela"),
                                                        ("yellow", "Rumena"),
                                                        ("purple", "Vijolična"),
                                                        (
                                                            "gradient_green_yellow",
                                                            "Zeleno-rumena",
                                                        ),
                                                        (
                                                            "gradient_purple_green",
                                                            "Vijolično-zelena",
                                                        ),
                                                    ],
                                                    label="Barva",
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.core.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "headline",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_left",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na levi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "buttons",
                                                                        wagtail.core.blocks.StreamBlock(
                                                                            [
                                                                                (
                                                                                    "button",
                                                                                    wagtail.core.blocks.StructBlock(
                                                                                        [
                                                                                            (
                                                                                                "style",
                                                                                                wagtail.core.blocks.ChoiceBlock(
                                                                                                    choices=[
                                                                                                        (
                                                                                                            "underlined",
                                                                                                            "Samo podčrtan",
                                                                                                        ),
                                                                                                        (
                                                                                                            "normal",
                                                                                                            "Z obrobo",
                                                                                                        ),
                                                                                                        (
                                                                                                            "background",
                                                                                                            "Z obrobo in ozadjem",
                                                                                                        ),
                                                                                                    ],
                                                                                                    label="Stil gumba",
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "text",
                                                                                                wagtail.core.blocks.CharBlock(
                                                                                                    label="Besedilo na gumbu"
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "page",
                                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                                    label="Stran"
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        label="Gumb",
                                                                                    ),
                                                                                )
                                                                            ],
                                                                            label="Gumbi",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Naslov",
                                                                template="home/blocks/headline.html",
                                                            ),
                                                        ),
                                                        (
                                                            "newsletter",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "title",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Naslov"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "description",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            label="Opis",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image_right",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Slika na desni",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "submit_button",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Besedilo na gumbu"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "checkbox_text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            label="Pogoji"
                                                                        ),
                                                                    ),
                                                                ],
                                                                icon="title",
                                                                label="Obvestilnik",
                                                                template="home/blocks/newsletter.html",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                default="",
                verbose_name="Vsebina",
            ),
        ),
    ]
