# Generated by Django 3.2.6 on 2021-08-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("home", "0012_auto_20210809_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Slika",
            ),
        ),
    ]
