# Generated by Django 3.2.6 on 2021-08-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_auto_20210810_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Ime kategorije"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ključ (če je prazno se avtomatsko ustvari iz imena)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorija rešitev",
                "verbose_name_plural": "Kategorije rešitev",
            },
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="claps_no",
            field=models.IntegerField(default=0, verbose_name="Število ploskov"),
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.solutioncategory",
            ),
        ),
    ]
