# Generated by Django 3.2.6 on 2021-08-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_solutioncategory_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Besedilo zgodbe')),
                ('name', models.EmailField(max_length=254, verbose_name='Ime uporabnika')),
                ('address', models.CharField(max_length=255, verbose_name='Naslov uporabnika')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Uporabniška zgodba',
                'verbose_name_plural': 'Uporabniške zgodbe',
            },
        ),
    ]
