# Generated by Django 3.2.6 on 2021-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rentalstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalstory',
            name='email',
            field=models.EmailField(default='janez.novak@example.com', max_length=254, verbose_name='E-mail uporabnika'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalstory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ime kategorije'),
        ),
    ]
