# Generated by Django 3.2.6 on 2021-08-16 08:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210816_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Vsebina'),
        ),
    ]
