# Generated by Django 3.2.6 on 2021-08-16 14:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_auto_20210816_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproblem",
            name="page",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Problem",
                to="home.solutionpage",
            ),
        ),
    ]
