# Generated by Django 3.2.6 on 2021-08-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_userproblem_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproblem",
            name="page",
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="user_problem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.userproblem",
            ),
        ),
    ]
