# Generated by Django 3.2.6 on 2021-08-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("home", "0038_auto_20210818_0833"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
