# Generated by Django 3.2.6 on 2021-08-20 07:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210820_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='related_problems',
            field=wagtail.core.fields.StreamField([('problem', wagtail.core.blocks.PageChooserBlock(label='Povezava do problema'))], null=True),
        ),
    ]
