# Generated by Django 3.2.6 on 2021-08-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_solutionpage_related_problems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalstory',
            options={'verbose_name': 'Najemniška izkušnja', 'verbose_name_plural': 'Najemniške izkušnje'},
        ),
    ]
