# Generated by Django 3.2.6 on 2021-08-23 12:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0046_alter_contentpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('body', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True, verbose_name='Vsebina')),
            ],
            options={
                'verbose_name': 'Urejanje naročnine',
                'verbose_name_plural': 'Urejanja naročnin',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='related_problems',
            field=wagtail.core.fields.StreamField([('problem', wagtail.core.blocks.PageChooserBlock(label='Povezava do problema'))], blank=True, null=True),
        ),
    ]
