# Generated by Django 3.2.6 on 2021-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_contentpage_modal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='modal_form_checkbox',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='modal_form_checkbox2',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='modal_form_checkbox_hide_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Forma - checkbox za skrito lokacijo'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='modal_form_checkbox_newsletter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Forma - checkbox za občasno elektronsko sporočilo'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='modal_form_checkbox_private',
            field=models.CharField(blank=True, max_length=255, verbose_name='Forma - checkbox za nejavno zgodbo'),
        ),
        migrations.AddField(
            model_name='rentalstory',
            name='hide_location',
            field=models.BooleanField(default=False, verbose_name='Zgodba naj se objavi brez lokacije'),
        ),
        migrations.AlterField(
            model_name='rentalstory',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ime uporabnika'),
        ),
    ]
