# Generated by Django 3.2.6 on 2021-08-25 11:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_solutionpage_new_problem_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionpage',
            name='new_problem_form',
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='newsletter_section',
            field=wagtail.core.fields.StreamField([('newsletter', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Naslov')), ('description', wagtail.core.blocks.RichTextBlock(label='Opis', required=False)), ('image_left', wagtail.images.blocks.ImageChooserBlock(label='Slika na levi', required=False)), ('image_right', wagtail.images.blocks.ImageChooserBlock(label='Slika na desni', required=False)), ('submit_button', wagtail.core.blocks.CharBlock(label='Besedilo na gumbu')), ('checkbox_text', wagtail.core.blocks.CharBlock(label='Tekst ob checkboxu'))]))], blank=True, null=True, verbose_name='Novičnik'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.solutioncategory', verbose_name='Kategorija'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='related_problems',
            field=wagtail.core.fields.StreamField([('problem', wagtail.core.blocks.PageChooserBlock(label='Povezava do problema'))], blank=True, null=True, verbose_name='Povezani problemi'),
        ),
    ]
