# Generated by Django 3.2.6 on 2021-08-25 12:17

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_auto_20210825_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solutionpage",
            name="newsletter_section",
        ),
        migrations.AddField(
            model_name="solutionpage",
            name="new_problem_section",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "new_problem",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(label="Naslov"),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Opis", required=False
                                    ),
                                ),
                                (
                                    "submit_button",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst na gumbu"
                                    ),
                                ),
                                (
                                    "checkbox_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst ob checkboxu"
                                    ),
                                ),
                            ],
                            label="Sekcija",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Nov problem",
            ),
        ),
    ]
