# Generated by Django 3.2.6 on 2021-08-30 08:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_solutionpage_new_problem_section_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionpage',
            name='new_problem_section_background_color',
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='new_problem_section',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('new_problem', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Naslov')), ('description', wagtail.core.blocks.RichTextBlock(label='Opis', required=False)), ('submit_button', wagtail.core.blocks.CharBlock(label='Tekst na gumbu')), ('checkbox_text', wagtail.core.blocks.CharBlock(label='Tekst ob checkboxu'))])), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'Bela'), ('yellow', 'Rumena'), ('purple', 'Vijolična'), ('gradient_green_yellow', 'Zeleno-rumena'), ('gradient_purple_green', 'Vijolično-zelena')], label='Barva'))], label='Sekcija'))], blank=True, null=True, verbose_name='Sekcija za oddat nov problem'),
        ),
    ]
