# Generated by Django 3.2.22 on 2023-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_storyformpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyformpage',
            name='intro_text',
            field=models.TextField(blank=True, null=True, verbose_name='Besedilo pred obrazcem'),
        ),
    ]
