# Generated by Django 3.2.22 on 2023-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0059_storyformpage_intro_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_description",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_form_button",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_form_checkbox_hide_location",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_form_checkbox_newsletter",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_form_checkbox_private",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="modal_title",
        ),
        migrations.AddField(
            model_name="storyformpage",
            name="discrimination_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Navodilo za opis diskriminacije"
            ),
        ),
        migrations.AddField(
            model_name="storyformpage",
            name="rental_story_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Navodilo za najemniške izkušnje"
            ),
        ),
    ]
