# Generated by Django 3.2.22 on 2023-12-18 20:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_contentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyformpage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Besedilo pred obrazcem'),
        ),
    ]
